spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eswasthya_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  #automatically update database schema
    show-sql: true  #Display sql queries in logs

server:
    port: 8080
    referer-policy: no-referrer

#    email configuration
spring.mail:
    host: smtp.gmail.com
    port: 587
    username: info.eswasthya.app@gmail.com
    password: gbyzwmhuqupfyspb
    properties:
      mail:
        smtp:
          trust: smtp.gmail.com
          starttls:
            enable: true
        auth: true


