spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eswasthya_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  #automatically update database schema
    show-sql: true  #Display sql queries in logs

server:
    port: 8080

