INSERT INTO disease (id, disease_name, disease_type)
VALUES
    (1, 'Common Cold', 'Infectious'),
    (2, 'Influenza', 'Infectious'),
    (3, 'Tuberculosis', 'Infectious'),
    (4, 'Malaria', 'Infectious'),
    (5, 'Hepatitis', 'Infectious'),
    (6, 'Coronary Artery Disease', 'Cardiovascular'),
    (7, 'Hypertension', 'Cardiovascular'),
    (8, 'Heart Failure', 'Cardiovascular'),
    (9, 'Stroke', 'Cardiovascular'),
    (10, 'Asthma', 'Respiratory'),
    (11, 'Chronic Obstructive Pulmonary Disease (COPD)', 'Respiratory'),
    (12, 'Bronchitis', 'Respiratory'),
    (13, 'Gastritis', 'Gastrointestinal'),
    (14, 'Peptic Ulcer Disease', 'Gastrointestinal'),
    (15, 'Irritable Bowel Syndrome (IBS)', 'Gastrointestinal'),
    (16, 'Gastroenteritis', 'Gastrointestinal'),
    (17, 'Alzheimer''s Disease', 'Neurological'),
    (18, 'Parkinson''s Disease', 'Neurological'),
    (19, 'Epilepsy', 'Neurological'),
    (20, 'Multiple Sclerosis', 'Neurological'),
    (21, 'Osteoarthritis', 'Musculoskeletal'),
    (22, 'Rheumatoid Arthritis', 'Musculoskeletal'),
    (23, 'Back Pain', 'Musculoskeletal'),
    (24, 'Fractures', 'Musculoskeletal'),
    (25, 'Depression', 'Mental Health'),
    (26, 'Anxiety Disorders', 'Mental Health'),
    (27, 'Bipolar Disorder', 'Mental Health'),
    (28, 'Schizophrenia', 'Mental Health'),
    (29, 'Breast Cancer', 'Neoplasms'),
    (30, 'Lung Cancer', 'Neoplasms'),
    (31, 'Colorectal Cancer', 'Neoplasms'),
    (32, 'Prostate Cancer', 'Neoplasms'),
    (33, 'Leukemia', 'Neoplasms'),
    (34, 'Lymphoma', 'Neoplasms');
